spring.application.name=sb-ecommerce-application

spring.h2.console.enabled=true
spring.datasource.url=jdbc:h2:mem:testdb


#spring.datasource.username=sa
#spring.datasource.password=
#spring.datasource.driverClassName=org.h2.Driver
#
#
#spring.h2.console.path=/h2-console

#recreation do not happen
#spring.jpa.hibernate.ddl-auto=update

# it allow to run h2 by giving security allow
#spring.h2.console.settings.web-allow-others=true

# its allows to show the sql commands in run --
#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.format_sql=create-drop
